export const ADD_ENTRY_TO_LIST = "ADD_ENTRY_TO_LIST";
export const DELETE_ENTRY_FROM_LIST = "DELETE_ENTRY_FROM_LIST";
export const CHANGE_BUYING_STATE = "CHANGE_BUYING_STATE";
export const SORT_BY_PRIORITY = "SORT_BY_PRIORITY";
export const SORT_ALPHABETICALLY = "SORT_ALPHABETICALLY";
